export enum PaymentMethod {
  ZALOPAY_SANDBOX = 'ZALOPAY_SANDBOX',
  MOMO_SANDBOX = 'MOMO_SANDBOX',
  VNPAY_SANDBOX = 'VNPAY_SANDBOX',
  COD_SANDBOX = 'COD_SANDBOX',
  BANK_SANDBOX = 'BANK_SANDBOX',
}
